### ISSUE TITLE
Travis-Ci fails using GHC 8.2.1

### ISSUE THREAD

**Issue by jonaprieto** [jonaprieto/athena#54]
Using this travis fails (something related with cabal-install)

```
  include:

    - env: TEST=MAIN GHC_VER=8.2.1 BUILD=CABAL CABAL_VER=1.24
      addons:
        apt:
          packages:
            - alex-3.1.7
            - cabal-install-1.24
            - ghc-8.2.1
            - happy-1.19.5
            - texlive-binaries
          sources:
            - hvr-ghc
```
